const PDFDocument = require('pdfkit');
const fs = require('fs');

const generateOrderPDF = (order, outputPath) => {
  const doc = new PDFDocument();

  // Pipe the PDF stream to a file
  doc.pipe(fs.createWriteStream(outputPath));

  // Title
  doc.fontSize(20).text('Order Summary', { align: 'center', underline: true });
  doc.moveDown(2);

  // Customer Details
  doc.fontSize(14).text('Customer Details', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(12).text(`Name: ${order.cName}`);
  doc.text(`Mobile: ${order.cMobile}`);
  doc.text(`Date: ${order.date}`);
  doc.moveDown(1);

  // Order Summary
  doc.fontSize(14).text('Order Summary', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(12).text(`Order ID: ${order.order_id}`);
  doc.text(`Total: ₹${order.total}`);
  doc.text(`Amount Paid: ₹${order.amountPaid}`);
  doc.text(`Balance: ₹${order.balance}`);
  doc.text(`Subtotal: ₹${order.subtotal}`);
  doc.text(`Borrow: ₹${order.borrow}`);
  doc.text(`Previous Borrow: ₹${order.previousborrow}`);
  doc.text(`Total Profit: ₹${order.totalProfit}`);
  doc.moveDown(1);

  // Order Items
  doc.fontSize(14).text('Order Items', { underline: true });
  doc.moveDown(0.5);
  order.orderItems.forEach((item, index) => {
    doc.fontSize(12).text(
      `${index + 1}. Product: ${item.product_name}, Unit Price: ₹${item.unitprice}, Quantity: ${item.quantity}, Total Cost: ₹${item.actualtotalcost}`
    );
    doc.moveDown(0.5);
  });

  // Footer
  doc.moveDown(2);
  doc.fontSize(10).text('Generated by Order Management System', { align: 'center' });

  // Finalize the document
  doc.end();
};

module.exports = generateOrderPDF;
